In [1]:
import numpy as np

In [4]:
a = np.random.rand(10, 10)

In [5]:
a

array([[0.83776734, 0.40497447, 0.72332833, 0.70821775, 0.72296801,
        0.22048395, 0.34688615, 0.11086363, 0.16986329, 0.27349351],
       [0.31657808, 0.23274099, 0.88985641, 0.48664208, 0.54239691,
        0.4448178 , 0.03880942, 0.76850557, 0.34039299, 0.9865498 ],
       [0.9731209 , 0.29062141, 0.41972455, 0.41661619, 0.27563458,
        0.13588803, 0.68362228, 0.75184838, 0.36240881, 0.13267372],
       [0.22628063, 0.8991541 , 0.02453208, 0.65133259, 0.77718127,
        0.53283523, 0.93842446, 0.54778677, 0.25036839, 0.69832702],
       [0.5253463 , 0.45097867, 0.52174345, 0.5409013 , 0.24686054,
        0.59113851, 0.18435775, 0.58895973, 0.87648983, 0.22850752],
       [0.95401229, 0.82423048, 0.70047429, 0.90808866, 0.1947487 ,
        0.97228192, 0.23411366, 0.78541054, 0.91540514, 0.81493836],
       [0.83154768, 0.67270586, 0.36715295, 0.95918391, 0.91164673,
        0.96115695, 0.32612539, 0.59163018, 0.58171745, 0.10648423],
       [0.49694013, 0.0069053 , 0.5250040

In [7]:
a.reshape(-1, 5)

array([[0.83776734, 0.40497447, 0.72332833, 0.70821775, 0.72296801],
       [0.22048395, 0.34688615, 0.11086363, 0.16986329, 0.27349351],
       [0.31657808, 0.23274099, 0.88985641, 0.48664208, 0.54239691],
       [0.4448178 , 0.03880942, 0.76850557, 0.34039299, 0.9865498 ],
       [0.9731209 , 0.29062141, 0.41972455, 0.41661619, 0.27563458],
       [0.13588803, 0.68362228, 0.75184838, 0.36240881, 0.13267372],
       [0.22628063, 0.8991541 , 0.02453208, 0.65133259, 0.77718127],
       [0.53283523, 0.93842446, 0.54778677, 0.25036839, 0.69832702],
       [0.5253463 , 0.45097867, 0.52174345, 0.5409013 , 0.24686054],
       [0.59113851, 0.18435775, 0.58895973, 0.87648983, 0.22850752],
       [0.95401229, 0.82423048, 0.70047429, 0.90808866, 0.1947487 ],
       [0.97228192, 0.23411366, 0.78541054, 0.91540514, 0.81493836],
       [0.83154768, 0.67270586, 0.36715295, 0.95918391, 0.91164673],
       [0.96115695, 0.32612539, 0.59163018, 0.58171745, 0.10648423],
       [0.49694013, 0.0069053 , 0.

In [8]:
a.reshape(5, -1)

array([[0.83776734, 0.40497447, 0.72332833, 0.70821775, 0.72296801,
        0.22048395, 0.34688615, 0.11086363, 0.16986329, 0.27349351,
        0.31657808, 0.23274099, 0.88985641, 0.48664208, 0.54239691,
        0.4448178 , 0.03880942, 0.76850557, 0.34039299, 0.9865498 ],
       [0.9731209 , 0.29062141, 0.41972455, 0.41661619, 0.27563458,
        0.13588803, 0.68362228, 0.75184838, 0.36240881, 0.13267372,
        0.22628063, 0.8991541 , 0.02453208, 0.65133259, 0.77718127,
        0.53283523, 0.93842446, 0.54778677, 0.25036839, 0.69832702],
       [0.5253463 , 0.45097867, 0.52174345, 0.5409013 , 0.24686054,
        0.59113851, 0.18435775, 0.58895973, 0.87648983, 0.22850752,
        0.95401229, 0.82423048, 0.70047429, 0.90808866, 0.1947487 ,
        0.97228192, 0.23411366, 0.78541054, 0.91540514, 0.81493836],
       [0.83154768, 0.67270586, 0.36715295, 0.95918391, 0.91164673,
        0.96115695, 0.32612539, 0.59163018, 0.58171745, 0.10648423,
        0.49694013, 0.0069053 , 0.52500402, 0